version: '3.8'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: faker_user
      POSTGRES_PASSWORD: faker_password
      POSTGRES_DB: faker_demo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: